"""initiale_tabellen

Revision ID: b1f0738f6559
Revises: 
Create Date: 2026-04-13 15:23:50.967781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b1f0738f6559'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shibboleth_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('rolle', sa.Enum('STANDARD', 'ADMIN', name='benutzerrolle'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_benutzer_shibboleth_id'), 'benutzer', ['shibboleth_id'], unique=True)
    op.create_table('geraete',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventar_nummer', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kategorie', sa.String(length=50), nullable=True),
    sa.Column('hersteller', sa.String(length=50), nullable=True),
    sa.Column('modell', sa.String(length=50), nullable=True),
    sa.Column('seriennummer', sa.String(length=100), nullable=True),
    sa.Column('standort', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('VERFUEGBAR', 'AUSGELIEHEN', 'RESERVIERT', 'DEFEKT', 'AUSSER_BETRIEB', name='geraetestatus'), nullable=False),
    sa.Column('anschaffungsdatum', sa.Date(), nullable=True),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seriennummer')
    )
    op.create_index(op.f('ix_geraete_inventar_nummer'), 'geraete', ['inventar_nummer'], unique=True)
    op.create_index(op.f('ix_geraete_kategorie'), 'geraete', ['kategorie'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('geraet_id', sa.Integer(), nullable=True),
    sa.Column('aktion', sa.Enum('ANGELEGT', 'BEARBEITET', 'STATUS_AENDERUNG', 'AUSLEIHE', 'VERLAENGERUNG', 'RUECKGABE', 'RESERVIERUNG', name='aktiontype'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['geraet_id'], ['geraete.id'], ),
    sa.ForeignKeyConstraint(['nutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_zeitstempel'), 'audit_logs', ['zeitstempel'], unique=False)
    op.create_table('ausleihen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geraet_id', sa.Integer(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('startdatum', sa.DateTime(), nullable=False),
    sa.Column('geplantes_rueckgabedatum', sa.DateTime(), nullable=False),
    sa.Column('tatsaechliches_rueckgabedatum', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AKTIV', 'UEBERFAELLIG', 'ABGESCHLOSSEN', name='ausleihstatus'), nullable=False),
    sa.Column('verlaengerungen_anzahl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geraet_id'], ['geraete.id'], ),
    sa.ForeignKeyConstraint(['nutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservierungen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geraet_id', sa.Integer(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('reserviert_fuer_datum', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AKTIV', 'ERFUELLT', 'STORNIERT', name='reservierungsstatus'), nullable=False),
    sa.ForeignKeyConstraint(['geraet_id'], ['geraete.id'], ),
    sa.ForeignKeyConstraint(['nutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservierungen')
    op.drop_table('ausleihen')
    op.drop_index(op.f('ix_audit_logs_zeitstempel'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_geraete_kategorie'), table_name='geraete')
    op.drop_index(op.f('ix_geraete_inventar_nummer'), table_name='geraete')
    op.drop_table('geraete')
    op.drop_index(op.f('ix_benutzer_shibboleth_id'), table_name='benutzer')
    op.drop_table('benutzer')
    # ### end Alembic commands ###
